In [4]:
import torch

torch.manual_seed(42)
x = torch.randn(10)

def softmax_standard(x):
    """numerically stable by subtracting max"""
    n = (x - x.max()).exp()
    return n / n.sum()

def softmax_base2_trick(x):
    """calculate 2^x instead of e^x"""
    RCP_LN2 = 1.4426950408889634  # = 1.0 / ln(2)
    n = torch.exp2((x - x.max()) * RCP_LN2)
    return n / n.sum()

a = torch.softmax(x, dim=0)
b = softmax_standard(x)
c = softmax_base2_trick(x)

print(a)
print(b)
print(c)
print("allclose(a, b)" ,torch.allclose(a, b))
print("allclose(b, c)", torch.allclose(b, c))


tensor([0.0747, 0.0607, 0.0675, 0.0672, 0.0174, 0.0443, 0.4856, 0.0282, 0.0847,
        0.0697])
tensor([0.0747, 0.0607, 0.0675, 0.0672, 0.0174, 0.0443, 0.4856, 0.0282, 0.0847,
        0.0697])
tensor([0.0747, 0.0607, 0.0675, 0.0672, 0.0174, 0.0443, 0.4856, 0.0282, 0.0847,
        0.0697])
allclose(a, b) True
allclose(b, c) True
